services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "8883:8883"  # Porta para MQTT
      - "8884:8884"  # Porta para WebSockets
    volumes:
      - "C:/www/servers/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "C:/www/servers/mosquitto/passwords.txt:/mosquitto/config/passwords.txt"
    restart: unless-stopped
